### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by crazyzlj** [lreis2415/SimDTA#1]
Please leave messages here if you have any question about SimDTA.

任何关于SimDTA的问题都可以在这里留言。

**Comment by CtrlLS** [comment]
老师您好！不好意思打扰您了，有个问题需要请教您，最近使用30*30m的DEM数据计算TWI指数时，在计算汇流面积SCA时，软件一直闪退，不知道是怎么回事，所以向您请教解决办法，真的麻烦老师了，感谢您！
![image](https://user-images.githubusercontent.com/101159800/189878751-429f78a2-0134-4714-931e-e3db05d8ac3d.png)

**Comment by crazyzlj** [comment]
应该是输入的DEM没有做投影变换，从截图上看，输入数据还是经纬度坐标（cellsize是0.00027），很可能导致计算时数值溢出的错误。

**Comment by CtrlLS** [comment]
收到，非常感谢您的指导！！！您辛苦了，祝生活愉快！



在 2022-09-19 10:11:00，"Liang-Jun Zhu" ***@***.***> 写道：

老师您好！不好意思打扰您了，有个问题需要请教您，最近使用30*30m的DEM数据计算TWI指数时，在计算汇流面积SCA时，软件一直闪退，不知道是怎么回事，所以向您请教解决办法，真的麻烦老师了，感谢您！

应该是输入的DEM没有做投影变换，从截图上看，输入数据还是经纬度坐标（cellsize是0.00027），很可能导致计算时数值溢出的错误。
